name: Build and Test BLAS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x configure

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run testbench
        run: ./test/testbench
